# -*- coding: utf-8 -*-
"""Tugas Besar - Visualisasi Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17pYIwYMEBgKqs_Eocjm2ZpiooKzGosjf

#Final Project Assignment

##Visualisasi Data IF-42-GAB01 [IKN]

Nama Anggota Kelompok:
*   Liyan Fajar Ramadhan
*   Hanif Reangga
*   Irfani Adri Maulana

#Final Project
"""

# Data handling
import pandas as pd
import numpy as np

# Bokeh libraries
from bokeh.io import output_file, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import row, column, gridplot
from bokeh.models.widgets import Tabs, Panel

"""Data set yang digunakan pada tugas besar 2 ini adalah data time series dari beberapa<br>
parameter saham yang terdiri dari:<br>
* Date: Tanggal pengambilan data
* Adjusted Close: Harga penutupan yang telah disesuaikan
* Volume: Jumlah transaksi
* High: Harga maksimum dalam periode waktu yang diberikan
* Low: Harga minimum dalam periode waktu yang diberikan
* Open: Waktu ketika stock mulai trading
* Close: Waktu ketika stock mengakhiri trading
* Name: Indeks pasar saham
"""

data = pd.read_csv('NYSE.csv', parse_dates=['Date'])
data

data["Name"] = "NYSE"

data1 = pd.read_csv('NASDAQ.csv', parse_dates=['Date'])
data1

data1["Name"] = "NASDAQ"

data

data1

frame = [data, data1]

df = pd.concat(frame)
df

"""###Level 1

Visualisasi data interaktif untuk menampilkan nilai “Adjusted Close” untuk setiap indeks 
pasar saham. Aspek interaktif minimum yang harus dimunculkan adalah <br> 
* default toolbar
* hover.

Teks yang muncul pada saat kursor diletakkan di atas titik data adalah
* nama 
indeks pasar saham 
* nilai parameter
"""

df['Name'].unique()

condition = (df['Name'] == 'NYSE') | (df['Name'] == 'NASDAQ')
Level_1 = df[condition]
Level_1= Level_1.loc[:, ['Date','Name','Adjusted Close']]
Level_1 = Level_1.sort_values(['Date', 'Name'])
Level_1.head()

output_notebook()

# Output to file
output_file('Level_1.html', 
            title='Nilai Adjusted Close untuk setiap indeks pasar saham')

# Isolate the data
nyse = Level_1[Level_1['Name'] == 'NYSE']
nasdaq = Level_1[Level_1['Name'] == 'NASDAQ']

# Create a ColumnDataSource object 
nyse_cds = ColumnDataSource(nyse)
nasdaq_cds = ColumnDataSource(nasdaq)

tooltips = [('Name', '@Name'), ('Adjusted Close', '$y{0.2f}')]

# Create and configure the figure
fig = figure(x_axis_type='datetime',
             plot_height=500, plot_width=1000,
             title='Nilai Adjusted Close untuk setiap indeks pasar saham',
             x_axis_label='Date', y_axis_label='Adjusted Close', tooltips=tooltips)

# Render 
fig.line('Date', 'Adjusted Close', 
         color='red', legend_label='NYSE',
         line_width=1, 
         source=nyse_cds)
fig.line('Date', 'Adjusted Close', 
         color='blue', legend_label='NASDAQ', 
         line_width=1,
         source=nasdaq_cds)


# Move the legend 
fig.legend.location = 'top_left'

# Show the plot
show(fig)

"""###Level 2

Lakukan semua instruksi pada kasus level 1. Tambahkan aspek interaktif yang
memungkinkan user memilih parameter yang akan ditampilkan: 
* Adjusted Close, 
* Volume, 
* High.<br>

Nilai parameter yang muncul pada hover tool harus disesuaikan dengan parameter yang dipilih.
"""

Level_2 = df
Level_2 = Level_2.sort_values(['Date', 'Name'])
Level_2.head()

# Isolate the data 
nyse = Level_2[Level_2['Name'] == 'NYSE']
nasdaq = Level_2[Level_2['Name'] == 'NASDAQ']

# Create a ColumnDataSource object
nyse_cds = ColumnDataSource(nyse)
nasdaq_cds = ColumnDataSource(nasdaq)

tooltips = [('Name', '@Name'), ('Adjusted Close', '$y{0.2f}'), ('Volume', '$y{0.2f}'), ('High', '$y{0.2f}')]

# Create and configure the figure
fig_adj = figure(x_axis_type='datetime',
             plot_height=500, plot_width=1000,
             title='Nilai Adjusted Close untuk setiap indeks pasar saham',
             x_axis_label='Date', y_axis_label='Adjusted Close', tooltips=tooltips)

fig_volume = figure(x_axis_type='datetime',
             plot_height=500, plot_width=1000,
             title='Nilai Adjusted Close untuk setiap indeks pasar saham',
             x_axis_label='Date', y_axis_label='Volume', tooltips=tooltips)
fig_high = figure(x_axis_type='datetime',
             plot_height=500, plot_width=1000,
             title='Nilai Adj CLose untuk setiap indeks pasar saham',
             x_axis_label='Date', y_axis_label='Day_Perc_Change', tooltips=tooltips)

# Render Adjusted Close
fig_adj.line('Date', 'Adjusted Close', 
         color='red', legend_label='NYSE',
         line_width=1, 
         source=nyse_cds)
fig_adj.line('Date', 'Adjusted Close', 
         color='blue', legend_label='NASDAQ', 
         line_width=1,
         source=nasdaq_cds)

# Render Volume
fig_volume.line('Date', 'Volume', 
         color='red', legend_label='NYSE',
         line_width=1, 
         source=nyse_cds)
fig_volume.line('Date', 'Volume', 
         color='blue', legend_label='NASDAQ', 
         line_width=1,
         source=nasdaq_cds)

# Render Volume
fig_high.line('Date', 'High', 
         color='red', legend_label='NYSE',
         line_width=1, 
         source=nyse_cds)
fig_high.line('Date', 'High', 
         color='blue', legend_label='NASDAQ', 
         line_width=1,
         source=nasdaq_cds)

# Move the legend
fig_adj.legend.location = 'top_left'
fig_volume.legend.location = 'top_left'
fig_high.legend.location = 'top_left'

from bokeh.io import output_file
from bokeh.models.widgets import Tabs, Panel

output_notebook()

# Output to file
output_file('Level_2.html', 
            title='Nilai Adjusted Close, Volume, High untuk setiap indeks pasar saham')

adj = Panel(child= fig_adj, title='Adjusted Close')
vol = Panel(child= fig_volume, title='Volume')
day = Panel(child= fig_high, title='High')

tabs = Tabs(tabs=[adj, vol, day])

show(tabs)

"""###Level 3

Lakukan semua instruksi pada kasus level 1 dan 2. Tambahkan aspek interaktif yang
memungkinkan user untuk menyembunyikan data untuk indeks pasar saham tertentu dengan
mengklik legend dari indeks tersebut.
"""

adj = Panel(child= fig_adj, title='Adjusted Close')
vol = Panel(child= fig_volume, title='Volume')
day = Panel(child= fig_high, title='High')

output_notebook()

# Output to file
output_file('Level_3.html', 
            title='Nilai Adjusted Close, Volume, High untuk setiap indeks pasar saham')

# Add interactivity to the legend
fig_adj.legend.click_policy = 'hide'
fig_volume.legend.click_policy = 'hide'
fig_high.legend.click_policy = 'hide'

# Visualize
show(tabs)